services:
  - type: web
    name: wish_list
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn wish_list.wsgi:application
    staticPublishPath: staticfiles
