services:
  - type: web
    name: wish_list
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_project_name.wsgi:application
    staticPublishPath: staticfiles
